# Generated by Django 6.0.3 on 2026-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_shippingaddress_shipping_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_address1',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_address2',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_zip_code',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_block',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_governorate',
            field=models.CharField(blank=True, choices=[('capital', 'Capital (العاصمة)'), ('hawalli', 'Hawalli (حولي)'), ('farwaniya', 'Farwaniya (الفروانية)'), ('ahmadi', 'Ahmadi (الأحمدي)'), ('jahra', 'Jahra (الجهراء)'), ('mubarak', 'Mubarak Al-Kabeer (مبارك الكبير)')], max_length=20),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_house',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='shipping_country',
            field=models.CharField(default='Kuwait', max_length=200),
        ),
    ]
