# Generated by Django 6.0.3 on 2026-03-23 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address1', models.CharField(blank=True, max_length=200, verbose_name='Block & Street')),
                ('address2', models.CharField(blank=True, max_length=200, verbose_name='House/Apartment')),
                ('governorate', models.CharField(blank=True, choices=[('capital', 'Capital (العاصمة)'), ('hawalli', 'Hawalli (حولي)'), ('farwaniya', 'Farwaniya (الفروانية)'), ('ahmadi', 'Ahmadi (الأحمدي)'), ('jahra', 'Jahra (الجهراء)'), ('mubarak', 'Mubarak Al-Kabeer (مبارك الكبير)')], max_length=20, verbose_name='Governorate')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='Area (e.g. Salmiya)')),
                ('country', models.CharField(blank=True, default='Kuwait', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
